skeleton
js-tasks-ru/htmlcss-20210610_yanina4 pull request #10
Opened 2021-06-27 22:40 UTC by yaninareshetco

task_6

2021-06-27 22:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 07:51 UTC, GSemikozov requested changes

2021-06-28 07:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    float: left;
флоаты ни в коем случае не используем - мы уже изучили флексы и гриды, для выравнивания надо брать один из этих способов)

2021-06-28 07:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
фиксированные размеры уберем - иначе на мобилке компонент вылезет за пределы экрана

2021-06-28 07:51 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
здесь и ниже фиксированные значения тоже уберем (если надо задать ширину линиям - то через проценты, чтобы они растягивались и сужались пропорционально вместе со всем блоком, а если ширину врапперу с линиями, чтобы он встал в один ряд с кружком - то тогда надо добавить еще один враппер по типу .skeleton__header, и использовать display: flex; вместо жеской фиксации размеров и флоатов)

2021-06-28 12:24 UTC, yaninareshetco commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
убрала

2021-06-28 13:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 14:14 UTC, yaninareshetco commented on 04-lection2/02-skeleton/skeleton.css
> +    float: left;
исправила

2021-06-28 14:15 UTC, yaninareshetco commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
исправила

2021-06-28 21:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 08:19 UTC, GSemikozov requested changes

2021-06-30 08:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line {
все элементыы скелетона должны быть оформлены по БЭМ: .line -> .skeleton__line, отдельно .lines не надо, раз есть .skeleton__lines, .lines_1 -> .skeleton__lines_1 (хотя цифра вместо имени модификатора по сути не нессет никакого смысла и вряд ли поможет другому девелоперу понять как устроена верстка =)), .lines_2 -> .skeleton__lines_2, .line_1 -> .skeleton__line_1 , .line_2 -> .skeleton__line_2

2021-06-30 20:38 UTC, yaninareshetco commented on 04-lection2/02-skeleton/skeleton.css
> +.line {
исправила

2021-07-01 21:02 UTC, GSemikozov approved these changes

2021-07-01 21:02 UTC, merged