task_7
js-tasks-ru/htmlcss-20210610_yanina4 pull request #12
Opened 2021-06-30 18:35 UTC by yaninareshetco

tooltip

2021-06-30 18:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-30 20:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 20:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 20:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-01 10:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-01 11:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-01 14:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-01 21:05 UTC, GSemikozov requested changes

2021-07-01 21:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.vector-2 {
вместо этих векторов - в стилях и соответственно в хтмл - лучше использовать полноценную иконку (можно так же заинлайнить свг)

2021-07-01 21:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
то что не относится к блоку - выносим

2021-07-01 23:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-01 23:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 09:25 UTC, yaninareshetco commented on 05-lection3/01-tooltip/tooltip.css
> +.vector-2 {
вставила полноценную иконку

2021-07-02 09:25 UTC, yaninareshetco commented on 05-lection3/01-tooltip/tooltip.css
> +body {
убрала

2021-07-02 10:59 UTC, GSemikozov approved these changes

2021-07-02 10:59 UTC, merged