task_8
js-tasks-ru/htmlcss-20210610_yanina4 pull request #13
Opened 2021-07-02 09:21 UTC by yaninareshetco

modal

2021-07-02 09:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-02 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-02 11:08 UTC, GSemikozov requested changes

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-close {
.modal-close -> .modal__сlose

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding-right: 15px;
лучше вместо ненужного отступа (что добавляет область самой кнопки и можно нажать рядом но не по крестику) указать например right: 15px

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <p>Amet minimmollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitacion veniam consequat sunt nostrud amet. Amet minim
class="modal__description" | class="modal__text"?

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__text {
это скорее не текст в целом, а какой-нибудь .modal__inner или .modal__content

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    box-shadow: 0 0 0 9999px rgba(196, 196, 196, 0.5);
а для чего такое размытие `9999px`?

2021-07-02 11:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
с самим модальным окном все ок, вот только оно должно позициониироваться относительно своего враппера которого нет и который должен позиционироваться относительно окна браузера через position: fixed, + растягиваться на 100vh и 100vw и иметь полупрозрачный фон. Соответственно, будет как-то так:
```
.modal {
    position: fixed;
top: 0;
left: 0;
width: 100vw;
height: 100vh;
background: ...;
}

.modal__window {
    // а тут как раз то, что сейчас в .modal - надо просто переименовать класс
}
```

2021-07-02 19:21 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +.modal-close {
исправила

2021-07-02 19:26 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +    padding-right: 15px;
исправила

2021-07-02 19:29 UTC, yaninareshetco commented on 05-lection3/02-modal/index.html
> +                <p>Amet minimmollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitacion veniam consequat sunt nostrud amet. Amet minim
исправила на modal__content

2021-07-02 19:29 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +.modal__text {
исправила на modal__content

2021-07-03 05:06 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +    box-shadow: 0 0 0 9999px rgba(196, 196, 196, 0.5);
чтоб на любой экран хватило. а как правильно?

2021-07-03 05:20 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +    box-shadow: 0 0 0 9999px rgba(196, 196, 196, 0.5);
после следующего коммента поняла

2021-07-03 20:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-03 20:44 UTC, yaninareshetco commented on 05-lection3/02-modal/modal.css
> +.modal {
исправила, цвет фона в rgba, по другому opacity так и не получилось сделать. Одновременно с фоном модальное окно становилось прозрачным

2021-07-04 09:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
да, отлично

2021-07-04 09:12 UTC, GSemikozov approved these changes

2021-07-04 09:13 UTC, merged