avatar
js-tasks-ru/htmlcss-20210610_yanina4 pull request #16
Opened 2021-07-08 13:07 UTC by yaninareshetco

2021-07-08 13:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-08 13:29 UTC, GSemikozov requested changes

2021-07-08 13:29 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
нет блока, но есть элемент wrapper)
в общем, что-то пошло не так, и произошло несоответствие разметки и стилей))

2021-07-08 13:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-08 13:39 UTC, yaninareshetco commented on 06-lection4/01-avatar/avatar.css
> +.avatar__wrapper {
исправила

2021-07-08 13:43 UTC, GSemikozov requested changes

2021-07-08 13:43 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    height: 100%;
так мы растянем аватар по родителю, и если родитель у нас будет body как сейчас - то аватар растянется на всю страницу;)))
в общем, height: 100%; + width: 100%; надо задать .avatar__img, а .avatar-у - надо задать фиксированные в пикселях размеры, как в дизайне

2021-07-09 12:30 UTC, yaninareshetco commented on 06-lection4/01-avatar/avatar.css
> +    height: 100%;
исправила

2021-07-09 13:18 UTC, GSemikozov approved these changes

2021-07-09 13:18 UTC, merged