icon
js-tasks-ru/htmlcss-20210610_yanina4 pull request #20
Opened 2021-07-13 20:24 UTC by yaninareshetco

2021-07-13 20:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-13 20:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-14 12:36 UTC, GSemikozov requested changes

2021-07-14 12:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.icon-arrow {
.icon-arrow + .icon-arrow_rotate вышли не по БЭМ и выпали за пределы элементов блока .accordion)

2021-07-14 12:36 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.icon-help {
нужно переписать класс по БЭМ - .tooltip__icon

2021-07-14 21:07 UTC, yaninareshetco commented on 03-lection1/02-accordion/accordion.css
> +.icon-arrow {
заменила на accordion__icon

2021-07-14 21:11 UTC, yaninareshetco commented on 05-lection3/01-tooltip/tooltip.css
> +.icon-help {
исправила

2021-07-15 13:34 UTC, GSemikozov approved these changes

2021-07-15 13:34 UTC, merged