scss-postcss
js-tasks-ru/htmlcss-20210610_yanina4 pull request #27
Opened 2021-07-29 12:18 UTC by yaninareshetco

2021-07-29 12:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-30 07:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-02 08:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-05 12:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-05 12:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-08 11:51 UTC, GSemikozov requested changes

2021-08-08 11:51 UTC, GSemikozov commented on 03-lection1/01-button/button.scss
> +@mixin button ($background:false, $color:falce, $border-color:false) {
можно обойтись без `:false` и без @if  - поскольку мы все равно точно знаем что все эти значения надо проставить

2021-08-08 11:51 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.scss
> +.accordion__item {
здесь и ниже - можно использовать вложенные селекторы, то есть вссе дочерние элементы поместить в класс блока

2021-08-08 11:51 UTC, GSemikozov commented on 07-lection5/04-input/input.scss
> +::placeholder {
глобально? лучше так не делать, пусть только для инпутов данного блока плейсхолдер будет такого цвета

2021-08-10 11:37 UTC, yaninareshetco commented on 03-lection1/01-button/button.scss
> +@mixin button ($background:false, $color:falce, $border-color:false) {
исправила

2021-08-10 11:42 UTC, yaninareshetco commented on 03-lection1/02-accordion/accordion.scss
> +.accordion__item {
исправила

2021-08-14 20:53 UTC, yaninareshetco commented on 07-lection5/04-input/input.scss
> +::placeholder {
исправила

2021-08-14 21:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-15 10:22 UTC, GSemikozov approved these changes

2021-08-15 10:22 UTC, merged