burger-menu
js-tasks-ru/htmlcss-20210610_yanina4 pull request #28
Opened 2021-09-02 04:20 UTC by yaninareshetco

2021-09-02 04:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-02 15:40 UTC, GSemikozov requested changes

2021-09-02 15:40 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +    top: 0;
для большей точности желательно еще указать left: 0

2021-09-11 21:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-13 20:09 UTC, yaninareshetco commented on 09-lection7/01-burger-menu/burger-menu.scss
> +    top: 0;
указала

2021-09-14 15:17 UTC, GSemikozov approved these changes

2021-09-14 15:17 UTC, merged