page
js-tasks-ru/htmlcss-20210610_yanina4 pull request #8
Opened 2021-06-25 21:59 UTC by yaninareshetco

Main_page_layout

2021-06-25 21:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-25 22:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-26 07:42 UTC, GSemikozov requested changes

2021-06-26 07:42 UTC, GSemikozov commented on components/page/page.css
> +width: 1440px;
.page лучше не будем ограничивать, есть ведь мониторы с гораздо бОльшей шириной)

2021-06-26 10:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-26 10:36 UTC, yaninareshetco commented on components/page/page.css
> +width: 1440px;
убрала

2021-06-26 10:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-26 20:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-27 07:44 UTC, GSemikozov requested changes

2021-06-27 07:44 UTC, GSemikozov commented on components/header/header.css
> +    padding-top: 96px;
в данном случае это все-таки марджин (= внешний отступ) - мы хотим отодвиинуть тайтл относительно других элементов сверху)

2021-06-27 07:44 UTC, GSemikozov commented on components/main/main.css
> +    position: absolute;
main секцию через absolute не надо, корректнее чтобы эта секция шла в основном потоке документа. Кроме того, здесь, а также у футера и хедера можно убрать фиксированную высоту (пусть растягиваются по своему внутреннему содержимому)

2021-06-27 07:44 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-top: 72px;
как и в случае с хедером - здесь скорее внешний отступ, то есть марджин

2021-06-27 18:35 UTC, yaninareshetco commented on components/header/header.css
> +    padding-top: 96px;
исправила

2021-06-27 18:35 UTC, yaninareshetco commented on components/main/main.css
> +    position: absolute;
исправила

2021-06-27 18:35 UTC, yaninareshetco commented on components/footer/footer.css
> +    padding-top: 72px;
исправила

2021-06-28 07:33 UTC, GSemikozov approved these changes

2021-06-28 07:33 UTC, merged